// frontend/components/ui/switch.tsx
'use client'

import clsx from 'clsx'
import type { ButtonHTMLAttributes } from 'react'

interface SwitchProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  pressed: boolean
}

export function Switch({ pressed, className, ...props }: SwitchProps) {
  return (
    <button
      type="button"
      aria-pressed={pressed}
      className={clsx(
        'relative inline-flex h-6 w-11 items-center rounded-full border border-border bg-muted transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring',
        className,
      )}
      {...props}
    >
      <span
        className={clsx(
          'inline-block h-4 w-4 rounded-full bg-foreground transition',
          pressed ? 'translate-x-6' : 'translate-x-1',
        )}
      />
      <span className="sr-only">テーマを切り替える</span>
    </button>
  )
}

// frontend/components/ui/Switch.vue
<template>
  <button
    type="button"
    class="relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer items-center rounded-full border border-border transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"
    :class="pressedValue ? 'bg-primary' : 'bg-border/70'"
    :aria-pressed="pressedValue"
    :aria-label="ariaLabel"
    @click="handleClick"
  >
    <span
      class="inline-block h-5 w-5 transform rounded-full bg-background transition"
      :class="pressedValue ? 'translate-x-5' : 'translate-x-1'"
    />
  </button>
</template>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{ pressed?: boolean; ariaLabel?: string }>()
const emit = defineEmits<{ (e: 'toggle'): void }>()

const pressedValue = computed(() => props.pressed ?? false)
const handleClick = () => emit('toggle')
</script>
