// frontend/components/dashboard/FiltersBar.vue
<template>
  <UiCard>
    <UiSelect
      label="基準日"
      :model-value="selectedDate"
      @update:model-value="(value) => emit('date-change', value)"
    >
      <option v-for="date in dates" :key="date" :value="date">
        {{ formatDate(date) }}
      </option>
    </UiSelect>
  </UiCard>
</template>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{ dates: string[]; selectedDate: string }>()
const emit = defineEmits<{ (e: 'date-change', value: string): void }>()

const dates = computed(() => props.dates)
const selectedDate = computed(() => props.selectedDate)

const formatDate = (iso: string) =>
  new Date(iso).toLocaleDateString('ja-JP', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
</script>

// frontend/components/dashboard/FiltersBar.tsx
'use client'

import { Card } from '@/components/ui/card'
import { Select } from '@/components/ui/select'

interface FiltersBarProps {
  dates: string[]
  selectedDate: string
  onDateChange: (date: string) => void
}

export function FiltersBar({ dates, selectedDate, onDateChange }: FiltersBarProps) {
  const formatDate = (iso: string) =>
    new Date(iso).toLocaleDateString('ja-JP', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    })

  return (
    <Card>
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <Select value={selectedDate} label="基準日" onChange={(event) => onDateChange(event.target.value)}>
          {dates.map((iso) => (
            <option key={iso} value={iso}>
              {formatDate(iso)}
            </option>
          ))}
        </Select>
        <div className="text-xs text-muted-foreground">
          <p>選択内容は自動的に反映されます</p>
          <p>最新値は約60秒周期で取得します</p>
        </div>
      </div>
    </Card>
  )
}
