// frontend/components/dashboard/NewsPanel.vue
<template>
  <UiCard title="関連ニュース">
    <div v-if="loading" class="space-y-3">
      <UiSkeleton height-class="h-6" />
      <UiSkeleton height-class="h-6" />
      <UiSkeleton height-class="h-6" />
    </div>
    <ul v-else class="space-y-4">
      <li
        v-for="item in items"
        :key="item.id"
        class="border-b border-border/60 pb-3 last:border-none"
      >
        <p class="text-sm font-semibold">{{ item.headline }}</p>
        <p class="mt-1 text-xs text-muted-foreground">{{ formatMeta(item) }}</p>
        <p v-if="item.summary" class="mt-2 text-sm text-muted-foreground">{{ item.summary }}</p>
      </li>
      <li v-if="items.length === 0" class="text-sm text-muted-foreground">
        表示できるニュースはありません。
      </li>
    </ul>
  </UiCard>
</template>

<script setup lang="ts">
import type { NewsItem } from '@/types/var'

defineProps<{ items: NewsItem[]; loading?: boolean }>()

const formatMeta = (item: NewsItem) => {
  const when = new Date(item.published_at)
  return `${item.source} • ${when.toLocaleTimeString('ja-JP', { hour: '2-digit', minute: '2-digit' })}`
}
</script>

// frontend/components/dashboard/NewsPanel.tsx
'use client'

import { Card } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import type { NewsItem } from '@/types/var'

interface NewsPanelProps {
  items: NewsItem[]
  loading?: boolean
}

export function NewsPanel({ items, loading = false }: NewsPanelProps) {
  const formatMeta = (item: NewsItem) => {
    const when = new Date(item.published_at)
    return `${item.source} • ${when.toLocaleTimeString('ja-JP', { hour: '2-digit', minute: '2-digit' })}`
  }

  return (
    <Card title="関連ニュース">
      {loading ? (
        <div className="space-y-3">
          <Skeleton heightClass="h-6" />
          <Skeleton heightClass="h-6" />
          <Skeleton heightClass="h-6" />
        </div>
      ) : (
        <ul className="space-y-4">
          {items.map((item) => (
            <li key={item.id} className="border-b border-border/60 pb-3 last:border-none">
              <p className="text-sm font-semibold">{item.headline}</p>
              <p className="mt-1 text-xs text-muted-foreground">{formatMeta(item)}</p>
              {item.summary && (
                <p className="mt-2 text-sm text-muted-foreground">{item.summary}</p>
              )}
            </li>
          ))}
          {items.length === 0 && (
            <li className="text-sm text-muted-foreground">表示できるニュースはありません。</li>
          )}
        </ul>
      )}
    </Card>
  )
}
