// frontend/components/dashboard/TimeseriesControls.tsx
'use client'

import { Card } from '@/components/ui/card'
import { Select } from '@/components/ui/select'
import { DEPARTMENT_PRODUCT_MAPPING } from './FiltersBar'

interface TimeseriesControlsProps {
  options: { value: string; label: string }[]
  selectedRic: string
  windowDays: number
  onAssetChange: (ric: string) => void
  onWindowChange: (days: number) => void
}

export function TimeseriesControls({
  options,
  selectedRic,
  windowDays,
  onAssetChange,
  onWindowChange,
}: TimeseriesControlsProps) {
  return (
    <Card>
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <Select
          value={selectedRic}
          label="部署 / 商品"
          onChange={(event) => onAssetChange(event.target.value)}
        >
          {DEPARTMENT_PRODUCT_MAPPING.map((option) => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </Select>
        <Select
          value={String(windowDays)}
          label="観測日数"
          onChange={(event) => onWindowChange(Number(event.target.value))}
          disabled
        >
          <option value="14">14日</option>
          <option value="30">30日</option>
          <option value="60">60日</option>
        </Select>
      </div>
    </Card>
  )
}

// frontend/components/dashboard/TimeseriesControls.vue
<template>
  <UiCard>
    <div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
      <UiSelect
        label="資産"
        :model-value="selectedRic"
        @update:model-value="(value) => emit('asset-change', value)"
      >
        <option v-for="option in options" :key="option.value" :value="option.value">
          {{ option.label }}
        </option>
      </UiSelect>
      <UiSelect
        label="観測日数"
        :model-value="String(windowDays)"
        @update:model-value="(value) => emit('window-change', Number(value))"
      >
        <option value="14">14日</option>
        <option value="30">30日</option>
        <option value="60">60日</option>
      </UiSelect>
    </div>
  </UiCard>
</template>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  options: { value: string; label: string }[]
  selectedRic: string
  windowDays: number
}>()

const emit = defineEmits<{ (e: 'asset-change', value: string): void; (e: 'window-change', value: number): void }>()

const selectedRic = computed(() => props.selectedRic)
const windowDays = computed(() => props.windowDays)
const options = computed(() => props.options)
</script>
